### PR TITLE
Color, font and text changing, because idk

### PR DESCRIPTION
**Pull request by szezjo**
Changes:
- button color that is the same as accents in Raino "full logo"
- font changed to Lato
- scale animation added
- text changes when hovering a button using :after, because... um... I like that kind of stuff? (if it's meh and you don't want it, just comment and I will remove it)

Peek1

### CODE REVIEW

**Comment by Roller23** [comment]
https://user-images.githubusercontent.com/25384028/113492383-4287af00-94d7-11eb-8676-a610cff91605.mov

Shrinks back on click, what do ya think

**Comment by szezjo** [comment]
Didn't think about that <3
Mlem!

**Review by Roller23 — DISMISSED** [review]
I am Buzz Lightyear and I approve of this

**Comment by adacienciala** [comment]
I kinda don't like two texts at the same time, "continue" doesn't serve any purpose then. I would go with one. Also - the phrase is "to infinity", not "to _the_ infinity".

**Review by TinyRogue — APPROVED** [review]
### Feature
I pretty much like the button's change on hover and fall in love with this shrinking - back and forth - it's **nooiiice flavor**, gj! =)
Yet, I'm not convinced about the text itself, it's not related neither to chat, nor to rain, but I can't figure out any other proposition as well, so if the others opt for this I'm in
### Style
How about using shorthands like `background` instead of `background-*` and `font` instead of `font-*` etc.?

**Review by byteingWolf — APPROVED** [review]
Button's change is captivating but I dont think there is a need to change the text

**Comment by Roller23** [comment]
@TinyRogue I feel like "background-color" and "font-size" are more descriptive than "background" (I also don't know what "font" refers to, is it font size or font family?)

Seems like half of us don't really love the phrase so we should decide whether to change it to something else or just leave it as "continue"

**Comment by Roller23** [comment]
aaa2
Yay or nay

**Comment by TinyRogue** [comment]
@Roller23 
On the one hand, I absolutely agree, on the other hand it is rather self-descriptive when You see property `font: calc(1em + 0.1vw) Helvetica, arial, serif` and way shorter than writing e.g. font-size, font-family. 

All in all, as long as we stick to one convention there's no need to worry. 👌🏻

**Comment by TinyRogue** [comment]
> 
> 
> aaa2
> 
> Yay or nay

Yay to me

**Comment by szezjo** [comment]
Changing text: I just thought that it would be sweet little unnecessary feature and I even wanted to change the phrase sometimes in updates to other stupid references... but yeah, it doesn't have to change on hover. It just looked funny and fancy for me.

New animation : Yay

Shorthand background and font: tbh I never liked them so I don't use them :v

**Review by adacienciala — APPROVED** [review]
With the new animation the text change has more sense and is more appealing to me. And I like Buzz Lightyear's reference. So now I'm happy with it.

**Pull request merged**
